steps:
  # Step 1: Build Angular Application
  - name: 'gcr.io/cloud-builders/Docker'
    args: ['build', '-t', 'angular', '.']
    dir: 'aishwaryar-cloudside-Task1--'

  # Step 2: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'Deployment.yml'
      - '-f'
      - 'service.yml'
    dir: 'aishwaryar-cloudside-angulare-env-'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '600s'
