  steps:
  # Step 1: Build Angular Application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'aishwaryar-cloudside-Task1--
'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'app'

  # Step 2: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'Deployment.yml'
      - '-f'
      - 'service.yml'
    dir: 'aishwaryar-cloudside-angulare-env-'

options:
  logging: CLOUD_LOGGING_ONLY

