steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'angular'
      - '.'
    timeout: '600s'

options:
  logging: 'CLOUD_LOGGING_ONLY
