steps:
  # Step 1: Pull Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'angular'
    timeout: '600s'

  # Step 2: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'Deployment.yml'
      - '-f'
      - 'service.yml'
    timeout: '600s'

options:
  logging: 'CLOUD_LOGGING_ONLY'







