steps:
  # Step 1: Build Angular Application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'angular', '.']
    dir: 'https://github.com/aishwaryar-cloudside/aishwaryar-cloudside-Task1--/blob/main/Dockerfile'

  # Step 2: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'Deployment.yml'
      - '-f'
      - 'service.yml'
    dir: 'https://github.com/aishwaryar-cloudside/aishwaryar-cloudside-angulare-env-'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '600s'
