steps:
  # Step 1: Pull Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'us-central1-docker.pkg.dev/vital-analogy-389705/my-repository/angular:ms1'
    timeout: '600s'

options:
  logging: 'CLOUD_LOGGING_ONLY'
